import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('[Reddimon Debug] Root layout rendering');
  
  return (
    <html lang="en">
      <head>
        <Script 
          src="https://track.reddimon.com/ki.js" 
          strategy="afterInteractive"
          onLoad={() => console.log('[Reddimon Debug] Script loaded successfully')}
          onError={(e) => console.error('[Reddimon Debug] Script failed to load:', e)}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
